const mockResults = [
  {
    adult: false,
    backdrop_path: "/hJXxDoCwchAuJ4K3gwtno2chgr8.jpg",
    genre_ids: [18],
    id: 491283,
    media_type: "movie",
    original_language: "en",
    original_title: "Judy",
    overview:
      "Winter 1968 and showbiz legend Judy Garland arrives in Swinging London to perform a five-week sold-out run at The Talk of the Town.",
    popularity: 21.379,
    poster_path: "/iqJhHjD6k6T07waELjMKDpQJUP.jpg",
    release_date: "2019-09-27",
    title: "Judy",
    video: false,
    vote_average: 6.8,
    vote_count: 723,
  },

  {
    backdrop_path: "/fTCoAXkLRxg9mWXzCFK2RTC4PFr.jpg",
    first_air_date: "1999-03-28",
    genre_ids: [16, 35, 10765],
    id: 615,
    media_type: "tv",
    name: "Futurama",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Futurama",
    overview:
      "The adventures of a late-20th-century New York City pizza delivery boy, Philip J. Fry, who, after being unwittingly cryogenically frozen for one thousand years, finds employment at Planet Express, an interplanetary delivery company in the retro-futuristic 31st century.",
    popularity: 117.105,
    poster_path: "/4olv2DdNUdg7oE6zoevbZbgEPsB.jpg",
    vote_average: 8.3,
    vote_count: 1676,
  },

  {
    adult: false,
    gender: 2,
    id: 5292,
    known_for: [
      {
        adult: false,
        backdrop_path: "/9vAoubhoZE8aSkUZoSfxs3UWZhO.jpg",
        genre_ids: [53, 28, 80],
        id: 156022,
        media_type: "movie",
        original_language: "en",
        original_title: "The Equalizer",
        overview:
          "McCall believes he has put his mysterious past behind him and dedicated himself to beginning a new, quiet life. But when he meets Teri, a young girl under the control of ultra-violent Russian gangsters, he can’t stand idly by – he has to help her. Armed with hidden skills that allow him to serve vengeance against anyone who would brutalize the helpless, McCall comes out of his self-imposed retirement and finds his desire for justice reawakened. If someone has a problem, if the odds are stacked against them, if they have nowhere else to turn, McCall will help. He is The Equalizer.",
        poster_path: "/9u4yW7yPA0BQ2pv9XwiNzItwvp8.jpg",
        release_date: "2014-09-24",
        title: "The Equalizer",
        video: false,
        vote_average: 7.2,
        vote_count: 6373,
      },
      {
        adult: false,
        backdrop_path: "/aPrrrGtSjXbw8XnpzsVJgF0ioq3.jpg",
        genre_ids: [28, 53, 878],
        id: 20504,
        media_type: "movie",
        original_language: "en",
        original_title: "The Book of Eli",
        overview:
          "A post-apocalyptic tale, in which a lone man fights his way across America in order to protect a sacred book that holds the secrets to saving humankind.",
        poster_path: "/1H1y9ZiqNFaLgQiRDDZLA55PviW.jpg",
        release_date: "2010-01-11",
        title: "The Book of Eli",
        video: false,
        vote_average: 6.8,
        vote_count: 4497,
      },
      {
        adult: false,
        backdrop_path: "/wOH0JO1QBfLyrkV5VJDR957LhNL.jpg",
        genre_ids: [12, 28, 37],
        id: 333484,
        media_type: "movie",
        original_language: "en",
        original_title: "The Magnificent Seven",
        overview:
          "Looking to mine for gold, greedy industrialist Bartholomew Bogue seizes control of the Old West town of Rose Creek. With their lives in jeopardy, Emma Cullen and other desperate residents turn to bounty hunter Sam Chisolm for help. Chisolm recruits an eclectic group of gunslingers to take on Bogue and his ruthless henchmen. With a deadly showdown on the horizon, the seven mercenaries soon find themselves fighting for more than just money once the bullets start to fly.",
        poster_path: "/ezcS78TIjgr85pVdaPDd2rSPVNs.jpg",
        release_date: "2016-09-14",
        title: "The Magnificent Seven",
        video: false,
        vote_average: 6.3,
        vote_count: 4468,
      },
    ],
    known_for_department: "Acting",
    media_type: "person",
    name: "Denzel Washington",
    popularity: 24.682,
    profile_path: "/cEU2Vrdo83izpGmOvbVAOz5jCof.jpg",
  },
];

module.exports = { mockResults };
